Code migrated to FASTAPI for ortelius-ms-textfile-crud
ortelius/ortelius-ms-textfile-crud pull request #7
Opened 2021-09-08 19:23 UTC by karamjotsingh

Migrated the code from Flask to FASTAPI for ortelius-ms-textfile-crud

2021-09-08 19:39 UTC, markyjackson-taulia approved these changes

2021-09-08 20:29 UTC, sbtaylor15 requested changes

2021-09-08 20:29 UTC, sbtaylor15 commented on main.py
> +async def saveFileContent(fileRequest: FileRequest):
Please add the missing parameter `request: Request`

2021-09-09 04:23 UTC, codeWithUtkarsh requested changes

2021-09-09 04:23 UTC, codeWithUtkarsh commented on main.py
> +engine = create_engine("postgresql+psycopg2://" + db_user + ":" + db_pass + "@" + db_host + "/" + db_name)
Please add port as well in the connection string. eg- 
`
create_engine("postgresql+psycopg2://" + db_user + ":" + db_pass + "@" + db_host +":"+ db_port + "/" + db_name)
`

2021-09-09 10:41 UTC, merged

2021-09-09 16:11 UTC, sbtaylor15 reviewed
/lgtm